# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/NEW/vivado/MultipleCycleCPU_Basys3/MultipleCycleCPU_Basys3.cache/wt [current_project]
set_property parent.project_path D:/NEW/vivado/MultipleCycleCPU_Basys3/MultipleCycleCPU_Basys3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  D:/NEW/vivado/MultipleCycleCPU_Basys3/MultipleCycleCPU_Basys3.srcs/sources_1/new/DataMEM.v
  D:/NEW/vivado/MultipleCycleCPU_Basys3/MultipleCycleCPU_Basys3.srcs/sources_1/new/PC.v
  D:/NEW/vivado/MultipleCycleCPU_Basys3/MultipleCycleCPU_Basys3.srcs/sources_1/new/RegisterFile.v
  D:/NEW/vivado/MultipleCycleCPU_Basys3/MultipleCycleCPU_Basys3.srcs/sources_1/new/InsMEM.v
  D:/NEW/vivado/MultipleCycleCPU_Basys3/MultipleCycleCPU_Basys3.srcs/sources_1/new/ALU.v
  D:/NEW/vivado/MultipleCycleCPU_Basys3/MultipleCycleCPU_Basys3.srcs/sources_1/new/ControlUnit.v
  D:/NEW/vivado/MultipleCycleCPU_Basys3/MultipleCycleCPU_Basys3.srcs/sources_1/new/DR.v
  D:/NEW/vivado/MultipleCycleCPU_Basys3/MultipleCycleCPU_Basys3.srcs/sources_1/new/SignZeroExtend.v
  D:/NEW/vivado/MultipleCycleCPU_Basys3/MultipleCycleCPU_Basys3.srcs/sources_1/new/IR.v
  D:/NEW/vivado/MultipleCycleCPU_Basys3/MultipleCycleCPU_Basys3.srcs/sources_1/new/Debounce.v
  D:/NEW/vivado/MultipleCycleCPU_Basys3/MultipleCycleCPU_Basys3.srcs/sources_1/new/bcd_scan_display.v
  D:/NEW/vivado/MultipleCycleCPU_Basys3/MultipleCycleCPU_Basys3.srcs/sources_1/new/MultipleCycleCPU.v
  D:/NEW/vivado/MultipleCycleCPU_Basys3/MultipleCycleCPU_Basys3.srcs/sources_1/new/CPU_display.v
}
read_xdc D:/NEW/vivado/MultipleCycleCPU_Basys3/MultipleCycleCPU_Basys3.srcs/constrs_1/new/basys3.xdc
set_property used_in_implementation false [get_files D:/NEW/vivado/MultipleCycleCPU_Basys3/MultipleCycleCPU_Basys3.srcs/constrs_1/new/basys3.xdc]

synth_design -top CPU_display -part xc7a35tcpg236-1
write_checkpoint -noxdef CPU_display.dcp
catch { report_utilization -file CPU_display_utilization_synth.rpt -pb CPU_display_utilization_synth.pb }
